/**
 * DataDock Download Worker
 * Serves files from R2 (or proxies from signed URLs) using short-lived
 * HMAC-signed tokens generated by the FastAPI backend.
 * The storage URL is never exposed to the end user.
 */

const TOKEN_MAX_AGE = 300; // seconds — must match FastAPI WORKER_TOKEN_TTL

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (!url.pathname.startsWith('/dl/')) {
      return new Response('Not Found', { status: 404 });
    }

    const rawToken = decodeURIComponent(url.pathname.slice(4));
    if (!rawToken) {
      return new Response('Missing token', { status: 400 });
    }

    // Token format:  <base64url-payload>.<hmac-hex>
    const dot = rawToken.lastIndexOf('.');
    if (dot === -1) {
      return new Response('Malformed token', { status: 400 });
    }

    const payloadB64 = rawToken.slice(0, dot);
    const sigHex     = rawToken.slice(dot + 1);

    // ── Verify HMAC-SHA256 ───────────────────────────────────────────────────
    const enc = new TextEncoder();
    const cryptoKey = await crypto.subtle.importKey(
      'raw',
      enc.encode(env.WORKER_SECRET),
      { name: 'HMAC', hash: 'SHA-256' },
      false,
      ['verify'],
    );
    const sigBytes = hexToBytes(sigHex);
    const valid = await crypto.subtle.verify(
      'HMAC', cryptoKey, sigBytes, enc.encode(payloadB64),
    );
    if (!valid) {
      return new Response('Invalid token', { status: 403 });
    }

    // ── Decode payload ───────────────────────────────────────────────────────
    let payload;
    try {
      payload = JSON.parse(b64urlDecode(payloadB64));
    } catch {
      return new Response('Bad payload', { status: 400 });
    }

    // ── Check expiry ─────────────────────────────────────────────────────────
    if (Math.floor(Date.now() / 1000) > payload.e) {
      return new Response(
        'Link expired — please go back and click Download again.',
        { status: 410, headers: { 'Content-Type': 'text/plain' } },
      );
    }

    const filename = payload.f || 'download';
    const ct       = payload.c || 'application/octet-stream';

    // ── Serve from R2 (storage URL never leaves this Worker) ─────────────────
    if (payload.t === 'r2') {
      const obj = await env.BUCKET.get(payload.k);
      if (!obj) {
        return new Response('File not found', { status: 404 });
      }
      const headers = buildHeaders(ct, filename, obj.size);
      return new Response(obj.body, { headers });
    }

    // ── Proxy from signed URL (Wasabi, BunnyCDN, fallback CDN, etc.) ─────────
    if (payload.t === 'url') {
      let upstream;
      try {
        upstream = await fetch(payload.u, {
          headers: { 'User-Agent': 'DataDock-Worker/1.0' },
        });
      } catch {
        return new Response('Upstream unreachable', { status: 502 });
      }
      if (!upstream.ok) {
        return new Response('Upstream error', { status: 502 });
      }
      const cl = upstream.headers.get('Content-Length');
      const headers = buildHeaders(ct, filename, cl ? parseInt(cl) : null);
      return new Response(upstream.body, { headers });
    }

    return new Response('Unknown token type', { status: 400 });
  },
};

// ── Helpers ──────────────────────────────────────────────────────────────────

function buildHeaders(contentType, filename, size) {
  const safe    = filename.replace(/[^\w.\-() ]/g, '_');
  const encoded = encodeURIComponent(filename);
  const headers = new Headers({
    'Content-Type':        contentType,
    'Content-Disposition': `attachment; filename="${safe}"; filename*=UTF-8''${encoded}`,
    'Cache-Control':       'no-store, no-cache',
    'X-Robots-Tag':        'noindex',
  });
  if (size) headers.set('Content-Length', String(size));
  return headers;
}

function hexToBytes(hex) {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.slice(i, i + 2), 16);
  }
  return bytes;
}

function b64urlDecode(str) {
  // Restore standard base64 padding and chars, then decode
  str = str.replace(/-/g, '+').replace(/_/g, '/');
  while (str.length % 4) str += '=';
  return atob(str);
}
