name               = "datadock-dl"
main               = "worker.js"
compatibility_date = "2024-09-23"
account_id         = "0d80b4f5f64a0c98fafa3c859b9165fe"

[[r2_buckets]]
binding     = "BUCKET"
bucket_name = "switchsrom"
